### ISSUE TITLE
Not founding resources

### ISSUE THREAD

**Issue by jlcarvalho** [daliwali/fortune-mongodb#9]
The current version doesn't found the resources on mongo 3.0, it occurs because the adapter uses IDs as strings and not as ObjectID.

Replace `ids` for `ids.map((id)=>new ObjectID(id))` should fix.

**Comment by daliwali** [comment]
Actually, I decided that `ObjectID` should just be avoided, because it's heuristically difficult to tell if a string should be cast to an `ObjectID` or not. In this commit https://github.com/daliwali/fortune-mongodb/commit/333139076a434fa70cf0ba5570cba5fc24668622 it just generates random strings as the ID on document creation.

**Comment by jlcarvalho** [comment]
Nice. Thanks.
